name: mac_vim

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  VIM_LSP_GO_VERSION: '1.16.2'
  VIM_LSP_GOPLS_VERSION: '0.6.6'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install MacVim
        shell: bash
        run: brew install macvim
      - name: Download test runner
        shell: bash
        run: git clone --depth 1 --branch v1.5.5 --single-branch https://github.com/thinca/vim-themis ~/themis
      - name: Install Go for gopls
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.VIM_LSP_GO_VERSION }}
      - name: Install gopls
        shell: bash
        run: |
          go get golang.org/x/tools/gopls@v${{ env.VIM_LSP_GOPLS_VERSION }}
          gopls version
        env:
          GO111MODULE: 'on'
      - name: Run tests
        shell: bash
        run: |
          export PATH=~/themis/bin:$PATH
          export THEMIS_VIM=vim
          vim --version
          themis
